name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: esimkowitz
        password: ${{ secrets.DOCKER_HUB_ESIMKOWITZ_PAT }}
        # Log out from the Docker registry at the end of a job
    - name: Docker Setup QEMU
      uses: docker/setup-qemu-action@v2.0.0
      with:
        platforms: arm64
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        file: Dockerfile
        platforms: arm64
        tags: "esimkowitz/sphero-rvr-ros2:latest"
