name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.0.0
      with:
        username: esimkowitz
        password: ${{ secrets.DOCKER_HUB_ESIMKOWITZ_PAT }}
        # Log out from the Docker registry at the end of a job
    - name: Build and push Docker images
      uses: docker/build-push-action@v3.1.1
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: Dockerfile
        # List of tags
        tags: "esimkowitz/sphero-rvr-ros2:latest"
